global:
  imagePullPolicy: Always
  imagePullSecrets:
    - ghcr-secret

api:
  image:
    repository: ghcr.io/amine12344/mlops-training-01/api
    tag: sha-5c10fab08d47acdfd742678a615852bccfae6457

frontend:
  image:
    repository: ghcr.io/amine12344/mlops-training-01/frontend
    tag: sha-5c10fab08d47acdfd742678a615852bccfae6457
