global:
  imagePullPolicy: Always
  imagePullSecrets:
    - ghcr-secret

api:
  image:
    repository: ghcr.io/amine12344/mlops-training-01/api
    tag: sha-b2e93c32f3d349db8ced1628aad57723fd7f761b

frontend:
  image:
    repository: ghcr.io/amine12344/mlops-training-01/frontend
    tag: sha-b2e93c32f3d349db8ced1628aad57723fd7f761b
