global:
  imagePullPolicy: Always
  imagePullSecrets:
    - ghcr-secret

api:
  image:
    repository: ghcr.io/amine12344/mlops-training-01/api
    tag: sha-20573b3553902ab9ebe2cd50d5a13d10c24ad869

frontend:
  image:
    repository: ghcr.io/amine12344/mlops-training-01/frontend
    tag: sha-20573b3553902ab9ebe2cd50d5a13d10c24ad869
