{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled (has "monitoring.coreos.com/v1" .Capabilities.APIVersions) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Values.monitoring.releaseName | default "kube-prometheus-stack" }}
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}